package AplikasiTugasSekolah;

import static AplikasiTugasSekolah.dbkoneksitugas.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arlya Dewi
 * Tgl 28/06/2025
 */
public class TugasSekolahFiks extends javax.swing.JFrame {
    DefaultTableModel DTM = new DefaultTableModel();
    
    /**
     * Creates new form TugasSekolah
     */
    public TugasSekolahFiks() {
    initComponents();

    try {
        tbltugas.setModel(DTM);
        DTM.addColumn("id");
        DTM.addColumn("Mapel");
        DTM.addColumn("Deskripsi");
        DTM.addColumn("Deadline");
        DTM.addColumn("Status");

        String[] opsiS = {"Sudah selesai", "Belum selesai"};
        Jstatus.removeAllItems();
        for (String opsi : opsiS) {
                Jstatus.addItem(opsi);
            }

        lsdttugas();
    } catch (SQLException ex) {
        Logger.getLogger(TugasSekolahFiks.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Gagal memuat data awal: " + ex.getMessage());
    }

    clearform();
    tombol(false);
    cSimpan.setEnabled(true);
    cKeluar.setEnabled(true);
    fieldAktif(false);
    Jstatus.setVisible(false);      
    }
    private void tombol(boolean opsi){
        cSimpan.setEnabled (opsi);
        cUbah.setEnabled (opsi);
        cHapus.setEnabled (opsi);
        cKeluar.setEnabled (opsi);
            
    }
    private void fieldAktif(boolean opsi){
        txid.setEditable(opsi);
        txmapel.setEditable(opsi);
        txdes.setEditable(opsi);
        txdeadline.setEditable(opsi);
        txstatus.setEditable(opsi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cSimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cHapus = new javax.swing.JButton();
        txid = new javax.swing.JTextField();
        cUbah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cKeluar = new javax.swing.JButton();
        txmapel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jstatus = new javax.swing.JComboBox<>();
        txdeadline = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txdes = new javax.swing.JTextField();
        txstatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltugas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cSimpan.setText("Baru");
        cSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSimpanActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        cHapus.setText("Hapus");
        cHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHapusActionPerformed(evt);
            }
        });

        txid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txidActionPerformed(evt);
            }
        });

        cUbah.setText("Ubah");
        cUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUbahActionPerformed(evt);
            }
        });

        jLabel2.setText("MATA PELAJARAN");

        cKeluar.setText("Keluar");
        cKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKeluarActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("TABEL DAFTAR TUGAS");

        jLabel3.setText("DESKRIPSI");

        Jstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Jstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JstatusActionPerformed(evt);
            }
        });

        jLabel4.setText("DEADLINE");

        jLabel5.setText("STATUS");

        tbltugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbltugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbltugas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txid)
                    .addComponent(txmapel)
                    .addComponent(txdes)
                    .addComponent(txdeadline)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txstatus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(cUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cKeluar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txmapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txdeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cSimpan)
                            .addComponent(cHapus)
                            .addComponent(cUbah)
                            .addComponent(cKeluar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(296, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSimpanActionPerformed
       if (cSimpan.getText().equals("Baru")) {
    clearform();
    fieldAktif(true);

    txstatus.setVisible(false);
    Jstatus.setVisible(true);

    cSimpan.setText("Simpan"); // GANTI INI!
    cKeluar.setText("Batal");
    cUbah.setEnabled(false);
    cHapus.setEnabled(false);
} else {
    // Validasi format deadline sebelum simpan
    String deadlineInput = txdeadline.getText();
    if (!deadlineInput.matches("\\d{4}-\\d{2}-\\d{2}")) {
        JOptionPane.showMessageDialog(this, "Format deadline salah. Gunakan format YYYY-MM-DD.");
        return; // Stop proses simpan
    }

    try {
        storeData();
        lsdttugas();
    } catch (SQLException ex) {
        Logger.getLogger(TugasSekolahFiks.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    cSimpan.setText("Baru");
    cKeluar.setText("Tutup");
    clearform();
    fieldAktif(false);

    txstatus.setVisible(true);
    Jstatus.setVisible(false);
}
    }//GEN-LAST:event_cSimpanActionPerformed

    private void cHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHapusActionPerformed
int opsi = JOptionPane.showOptionDialog(
    this,
    "Yakin akan menghapus data dengan ID " + txid.getText() + "?",
    "Konfirmasi Hapus Data",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,
    null,
    null
);

if (opsi == JOptionPane.YES_OPTION) {
    try {
        destroyData();
        lsdttugas();
        clearform();
        cHapus.setEnabled(false);
        cUbah.setEnabled(false);
    } catch (SQLException ex) {
        Logger.getLogger(TugasSekolahFiks.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + ex.getMessage());
    }
}

    }//GEN-LAST:event_cHapusActionPerformed

    private void txidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txidActionPerformed

    private void cUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUbahActionPerformed
        if(cUbah.getText().equals("Ubah")){
            cUbah.setText("Simpan");
            cKeluar.setText("Batal");
            cSimpan.setEnabled(false);
            cHapus.setEnabled(false);
            fieldAktif(true);
            txid.setEditable(false);
            txstatus.setVisible(false);
            Jstatus.setVisible(true);
            Jstatus.setSelectedItem(txstatus.getText());

        }else{

            try {
                updateData();
                lsdttugas();
            } catch (SQLException ex) {
                Logger.getLogger(TugasSekolahFiks.class.getName()).log(Level.SEVERE, null, ex);
            }

            cUbah.setText("Ubah");
            cKeluar.setText("Batal");
            cSimpan.setEnabled(true);
            cUbah.setEnabled(false);
            txstatus.setVisible(true);
            Jstatus.setVisible(false);
            fieldAktif(false);
            clearform();
        }
    }//GEN-LAST:event_cUbahActionPerformed

    private void cKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKeluarActionPerformed
 if (cKeluar.getText().equals("Tutup")) {
    int opsi = JOptionPane.showOptionDialog(this, 
        "Yakin akan menutup aplikasi?", 
        "Konfirmasi Tutup Aplikasi?", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE, 
        null, null, null);
    
    if (opsi == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
} else {
    cKeluar.setText("Tutup");
    cSimpan.setText("Baru");
    cUbah.setText("Ubah");
    cSimpan.setEnabled(true);
    cUbah.setEnabled(false);
    Jstatus.setVisible(false);
    txstatus.setVisible(true);
    fieldAktif(false);
    clearform();
}
    }//GEN-LAST:event_cKeluarActionPerformed

    private void tbltugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltugasMouseClicked
txid.setText(tbltugas.getValueAt(tbltugas.getSelectedRow(), 0).toString());
txmapel.setText(tbltugas.getValueAt(tbltugas.getSelectedRow(), 1).toString());
txdes.setText(tbltugas.getValueAt(tbltugas.getSelectedRow(), 2).toString());
txdeadline.setText(tbltugas.getValueAt(tbltugas.getSelectedRow(), 3).toString());
txstatus.setText(tbltugas.getValueAt(tbltugas.getSelectedRow(), 4).toString());

// Update isi JComboBox berdasarkan data status
Jstatus.setSelectedItem(txstatus.getText());

cUbah.setEnabled(true);
cHapus.setEnabled(true);

    }//GEN-LAST:event_tbltugasMouseClicked

    private void JstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasSekolahFiks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasSekolahFiks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasSekolahFiks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasSekolahFiks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasSekolahFiks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jstatus;
    private javax.swing.JButton cHapus;
    private javax.swing.JButton cKeluar;
    private javax.swing.JButton cSimpan;
    private javax.swing.JButton cUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltugas;
    private javax.swing.JTextField txdeadline;
    private javax.swing.JTextField txdes;
    private javax.swing.JTextField txid;
    private javax.swing.JTextField txmapel;
    private javax.swing.JTextField txstatus;
    // End of variables declaration//GEN-END:variables
 private void lsdttugas() throws SQLException {
        Connection cnn = koneksi();

        DTM.getDataVector().removeAllElements();
        DTM.fireTableDataChanged();

        if (!cnn.isClosed()) {
            PreparedStatement PS = cnn.prepareStatement("SELECT * FROM tugas;");
            ResultSet RS = PS.executeQuery();
            while (RS.next()) {
                Object[] dttugas = new Object[5];
                dttugas[0] = RS.getString("id");
                dttugas[1] = RS.getString("Mapel");
                dttugas[2] = RS.getString("Deskripsi");
                dttugas[3] = RS.getString("Deadline");
                dttugas[4] = RS.getString("Status");
                DTM.addRow(dttugas);
            }
            cnn.close();
        }
    }

    private void clearform() {
        txid.setText("");
        txmapel.setText("");
        txdes.setText("");
        txdeadline.setText("");
        txstatus.setText("");
    }

    private void storeData() throws SQLException {
    Connection cnn = koneksi();
    String id = txid.getText(); // ambil ID dari input
    String mapel = txmapel.getText();
    String deskripsi = txdes.getText();
    String deadline = txdeadline.getText();
    String status = String.valueOf(Jstatus.getSelectedItem());

    if (!cnn.isClosed()) {
        PreparedStatement PS = cnn.prepareStatement(
            "INSERT INTO tugas (id, Mapel, Deskripsi, Deadline, Status) VALUES (?, ?, ?, ?, ?);"
        );
        PS.setString(1, id);
        PS.setString(2, mapel);
        PS.setString(3, deskripsi);
        PS.setString(4, deadline);
        PS.setString(5, status);
        PS.executeUpdate();
        cnn.close();
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
    }
}

private void updateData() throws SQLException {
    Connection cnn = koneksi();
    String id = txid.getText();
    String mapel = txmapel.getText();
    String deskripsi = txdes.getText();
    String deadline = txdeadline.getText();
    String status = String.valueOf(Jstatus.getSelectedItem());

    if (!cnn.isClosed()) {
        PreparedStatement PS = cnn.prepareStatement(
            "UPDATE tugas SET Mapel = ?, Deskripsi = ?, Deadline = ?, Status = ? WHERE id = ?;"
        );
        PS.setString(1, mapel);
        PS.setString(2, deskripsi);
        PS.setString(3, deadline);
        PS.setString(4, status);
        PS.setString(5, id); // WHERE id = ?
        int rows = PS.executeUpdate();
        cnn.close();

        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
        } else {
            JOptionPane.showMessageDialog(this, "Data gagal diubah. ID tidak ditemukan.");
        }
    }
}

    private void destroyData() throws SQLException {
        Connection cnn = koneksi();
        String id = txid.getText();

        if (!cnn.isClosed()) {
            PreparedStatement PS = cnn.prepareStatement("DELETE FROM tugas WHERE id = ?;");
            PS.setString(1, id);
            int rows = PS.executeUpdate();
            cnn.close();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus. ID tidak ditemukan.");
            }
        }
    }
}

